import { RootState } from "./store";

const initialState: RootState = {
  customers: [
    {
      key: "1",
      firstName: "John",
      lastName: "Brown",
      age: 32,
      address: "New York No. 1 Lake Park",
      tags: {
        cool: false,
        developer: true,
        loser: false,
        nice: true,
        teacher: false,
      },
      memo: "memo",
    },
    {
      key: "2",
      firstName: "Jim",
      lastName: "Green",
      age: 42,
      address: "London No. 1 Lake Park",
      tags: {
        cool: true,
        developer: false,
        loser: false,
        nice: true,
        teacher: true,
      },
    },
    {
      key: "3",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "4",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "5",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: false,
        developer: false,
        loser: false,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "6",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "7",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "8",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "9",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "10",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "11",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "12",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "13",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "14",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "15",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "16",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "17",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "18",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "19",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "20",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "21",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "22",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "23",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "24",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "25",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "26",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "27",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "28",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      key: "29",
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
  ],
};

export default initialState;
