import { RootState } from "./store";

const initialState: RootState = {
  user: {
    accessToken: "",
    client: "",
    uid: "",
    isSignedIn: false,
  },
  customers: [
    {
      id: 1,
      firstName: "John",
      lastName: "Brown",
      age: 32,
      address: "New York No. 1 Lake Park",
      tags: {
        cool: false,
        developer: true,
        loser: false,
        nice: true,
        teacher: false,
      },
      memo: "memo",
    },
    {
      id: 2,
      firstName: "Jim",
      lastName: "Green",
      age: 42,
      address: "London No. 1 Lake Park",
      tags: {
        cool: true,
        developer: false,
        loser: false,
        nice: true,
        teacher: true,
      },
    },
    {
      id: 3,
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      id: 4,
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      id: 5,
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: false,
        developer: false,
        loser: false,
        nice: false,
        teacher: false,
      },
    },
    {
      id: 6,
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      id: 7,
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      id: 8,
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      id: 9,
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      id: 10,
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      id: 11,
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      id: 12,
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      id: 13,
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      id: 14,
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
    {
      id: 15,
      firstName: "Joe",
      lastName: "Black",
      age: 32,
      address: "Sidney No. 1 Lake Park",
      tags: {
        cool: true,
        developer: true,
        loser: true,
        nice: false,
        teacher: false,
      },
    },
  ],
};

export default initialState;
